#line 2 "1705043.c"

#line 4 "1705043.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 63
#define YY_END_OF_BUFFER 64
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[170] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   64,   62,   33,   44,   62,   24,    1,   19,
       62,   53,   25,   26,   18,   31,   18,   62,   19,   46,
       32,   21,   22,   21,   45,   29,   30,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   27,   62,   28,
       61,   60,   61,   59,   55,   58,   57,   58,   56,   37,
       35,   37,   37,   41,   40,   41,   39,   43,   42,   43,
       44,   21,   23,    0,   54,   53,    0,   20,   47,   34,
       38,   47,   46,   51,   51,   45,   45,   45,   45,   45,
       45,    6,   45,   45,   45,    2,   45,   45,   45,   45,

       45,   60,   57,   35,   36,   40,   42,   52,   48,   53,
        0,    0,   52,    0,   47,    0,   50,   47,   45,   45,
       45,   45,   45,   45,   45,   45,    4,    8,   45,   45,
       45,   45,   52,   48,   53,    0,   47,   49,   50,   45,
       15,    9,   45,   45,   45,    3,   45,   45,   45,   12,
       45,   49,    7,   45,   45,   45,   10,   45,   45,    5,
       45,   45,   11,   13,   14,   45,   16,   17,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    1,   20,   21,
       22,   23,    1,    1,   24,   24,   24,   24,   25,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       26,   27,   28,    1,   29,    1,   30,   31,   32,   33,

       34,   35,   24,   36,   37,   24,   38,   39,   24,   40,
       41,   24,   24,   42,   43,   44,   45,   46,   47,   24,
       24,   24,   48,   49,   50,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[51] =
    {   0,
        1,    2,    1,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    4,    1,    5,    5,    1,
        1,    1,    1,    5,    5,    1,    3,    1,    6,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    1,    1,    1
    } ;

static const flex_int16_t yy_base[181] =
    {   0,
        0,    0,   48,   52,   77,  121,   56,   58,   60,   62,
       68,   70,  272,  334,  334,  334,  268,  248,  334,  334,
      259,   67,  334,  334,  253,  334,  249,   59,   73,   80,
      334,  241,  240,  239,    0,  334,  334,  218,   52,   50,
      220,   61,   57,  224,  210,  214,  218,  334,  204,  334,
      334,  334,  249,  334,  334,  334,  334,  248,  334,  334,
      334,  247,  232,  334,  334,  245,  334,  334,  334,  242,
      334,  334,  334,  234,  334,  101,  162,  334,   97,  334,
      334,  115,  119,  225,  157,    0,  205,  195,  207,  196,
      199,  188,  189,  188,  186,    0,  182,  181,  187,  186,

      185,  334,  334,  334,  334,  334,  334,  334,  334,  109,
      200,  212,  120,  166,  180,  127,  123,  142,  186,  181,
      169,  163,  173,  170,  166,  165,    0,    0,  149,  139,
      145,  135,  123,  334,  150,  238,  172,  194,  168,  131,
        0,    0,  129,  119,  123,    0,  116,  116,  122,    0,
       92,  201,    0,   80,   74,   75,    0,   66,   65,    0,
       22,   13,    0,    0,    0,   19,    0,    0,  334,  284,
      290,  296,  302,  308,  313,  315,  316,  321,  325,  328
    } ;

static const flex_int16_t yy_def[181] =
    {   0,
      169,    1,  170,  170,  171,  171,  172,  172,  173,  173,
      174,  174,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  175,  169,  169,  169,  169,  169,  169,  169,  176,
      169,  169,  169,  169,  177,  169,  169,  177,  177,  177,
      177,  177,  177,  177,  177,  177,  177,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  178,  169,  179,  178,  169,  169,  169,
      169,  169,  176,  176,  176,  177,  177,  177,  177,  177,
      177,  177,  177,  177,  177,  177,  177,  177,  177,  177,

      177,  169,  169,  169,  169,  169,  169,  169,  169,  179,
      178,  169,  180,  169,  169,  169,  169,   85,  177,  177,
      177,  177,  177,  177,  177,  177,  177,  177,  177,  177,
      177,  177,  180,  169,  180,  169,  169,  169,  169,  177,
      177,  177,  177,  177,  177,  177,  177,  177,  177,  177,
      177,  169,  177,  177,  177,  177,  177,  177,  177,  177,
      177,  177,  177,  177,  177,  177,  177,  177,    0,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169
    } ;

static const flex_int16_t yy_nxt[385] =
    {   0,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   20,   25,   26,   27,   28,   29,   30,   30,   31,
       32,   33,   34,   35,   35,   36,   14,   37,   35,   35,
       38,   39,   40,   41,   42,   35,   43,   35,   35,   35,
       35,   44,   45,   35,   35,   46,   47,   48,   49,   50,
       52,   53,  168,   54,   52,   53,  167,   54,   61,   62,
       61,   62,   65,   66,   65,   66,  166,   63,   74,   63,
       69,   70,   69,   70,   55,   75,   79,   79,   55,   57,
       58,   88,   59,   91,   80,   59,   67,   89,   67,   81,
       92,   96,   90,   77,   59,   82,   97,   83,   83,   94,

      165,   95,   74,   59,   85,  164,   59,   59,  163,  109,
       74,   59,  162,   85,   79,   79,   59,  108,   59,  161,
       59,  114,   59,   57,   58,  160,   59,  111,  134,   59,
      114,  169,  115,  115,   82,  111,   83,   83,   59,  114,
      139,  139,  117,   85,  137,  137,  136,   59,  114,  136,
       59,   59,   85,  159,  169,   59,  169,  158,  169,  157,
       59,  156,   59,  155,   59,  154,   59,  112,  153,  116,
      113,  116,  117,  151,  118,  118,  136,  150,  116,   76,
      116,  117,  149,  137,  137,  139,  139,  117,   76,  137,
      137,   76,   76,  148,  147,  138,   76,  115,  115,  146,

      145,   76,  144,   76,  114,   76,  143,   76,  133,  152,
      142,  152,  152,  114,  141,  140,  152,  110,  152,  152,
      134,  132,  131,  130,  129,  128,  110,  127,  126,  110,
      110,  125,  124,  123,  110,  122,  121,  120,  119,  110,
      169,  110,  108,  110,  107,  110,  135,  106,  105,  104,
      103,  102,   73,  101,  100,  135,   99,   98,   93,   87,
       72,   72,   72,   78,  135,   78,   73,  135,  135,   72,
       71,  169,  135,  169,  169,  169,  169,  135,  169,  135,
      169,  135,  169,  135,   51,   51,   51,   51,   51,   51,
       56,   56,   56,   56,   56,   56,   60,   60,   60,   60,

       60,   60,   64,   64,   64,   64,   64,   64,   68,   68,
       68,   68,   68,   68,   76,   76,  169,   76,   84,   84,
       86,   86,   74,   74,  169,   74,  110,  110,  169,  110,
      135,  169,  135,   13,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169
    } ;

static const flex_int16_t yy_chk[385] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    3,  166,    3,    4,    4,  162,    4,    7,    7,
        8,    8,    9,    9,   10,   10,  161,    7,   22,    8,
       11,   11,   12,   12,    3,   22,   28,   28,    4,    5,
        5,   39,    5,   40,   29,    5,    9,   39,   10,   29,
       40,   43,   39,   22,    5,   30,   43,   30,   30,   42,

      159,   42,   76,    5,   30,  158,    5,    5,  156,   76,
      110,    5,  155,   30,   79,   79,    5,  110,    5,  154,
        5,   79,    5,    6,    6,  151,    6,   76,  113,    6,
       79,  133,   82,   82,   83,  110,   83,   83,    6,   82,
      117,  117,  116,   83,  116,  116,  113,    6,   82,  133,
        6,    6,   83,  149,  118,    6,  118,  148,  135,  147,
        6,  145,    6,  144,    6,  143,    6,   77,  140,   85,
       77,   85,   85,  132,   85,   85,  135,  131,  114,   77,
      114,  114,  130,  114,  114,  139,  139,  137,   77,  137,
      137,   77,   77,  129,  126,  115,   77,  115,  115,  125,

      124,   77,  123,   77,  115,   77,  122,   77,  111,  138,
      121,  138,  138,  115,  120,  119,  152,  111,  152,  152,
      112,  101,  100,   99,   98,   97,  111,   95,   94,  111,
      111,   93,   92,   91,  111,   90,   89,   88,   87,  111,
       84,  111,   74,  111,   70,  111,  136,   66,   63,   62,
       58,   53,   49,   47,   46,  136,   45,   44,   41,   38,
       34,   33,   32,   27,  136,   25,   21,  136,  136,   18,
       17,   13,  136,    0,    0,    0,    0,  136,    0,  136,
        0,  136,    0,  136,  170,  170,  170,  170,  170,  170,
      171,  171,  171,  171,  171,  171,  172,  172,  172,  172,

      172,  172,  173,  173,  173,  173,  173,  173,  174,  174,
      174,  174,  174,  174,  175,  175,    0,  175,  176,  176,
      177,  177,  178,  178,    0,  178,  179,  179,    0,  179,
      180,    0,  180,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  169,
      169,  169,  169,  169
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "1705043.l"





#line 10 "1705043.l"
#include<bits/stdc++.h>
using namespace std;
#include "symbol_table.cpp"


int lineCount = 1;
int errorCount = 0;
char buf[100000];
char buf2[100000];
char *s;
char *s2;

int lineStart = 0;
bool finished = true;

ofstream token_file("1705043_token.txt");
ofstream log_file("1705043_log.txt");
SymbolTable* symboltable = new SymbolTable(7);


void PrintKeyword(string token, string lexeme, int lineNo){
        token_file <<"<" << token<< "> ";
        log_file << "Line no " << lineNo <<  ": Token "<<"<" << token << ">  Lexeme " << lexeme << " found" << endl;
    
}

void PrintOperator(string token, string lexeme,  int lineNo){

    token_file <<"<" << token <<", "<<lexeme<<"> ";
    log_file << "Line no " << lineNo <<  ": Token "<<"<" << token << ">  Lexeme " << lexeme << " found" << endl;
    if(lexeme=="{"){
        symboltable->EnterScope();
        }
    else if(lexeme=="}"){
        symboltable->ExitScope();
    }
}

void PrintIdentifier(string token, string lexeme, int lineNo){
    token_file <<"<" << token <<", "<<lexeme<<"> ";
    log_file << "Line no " << lineNo <<  ": Token "<<"<" << token << ">  Lexeme " << lexeme << " found" << endl;
    
    SymbolInfo* symbol = new SymbolInfo(lexeme, token);
    bool inserted = symboltable->Insert(*symbol);
    if(inserted != false)
        symboltable->PrintAllTables(log_file);
    else
        log_file<<lexeme<<" already exists in current ScopeTable"<<endl;
}


void PrintComment(int lineNo, bool error){
    if(error){
        log_file << "Line no " << lineNo << "Unfinished Comment " << buf << " found" << endl;
        memset(buf, 0, sizeof(buf));
        memset(buf2, 0, sizeof(buf2));
    }
    else{
        log_file << "Line no " << lineNo << ": Token "<< "<COMMENT>" <<" Lexeme " << buf << " found" << endl;
        memset(buf, 0, sizeof(buf));
        memset(buf2, 0, sizeof(buf2));
    }
}

void PrintString(int lineNo){
    token_file <<"<STRING, "<< buf2 << " > ";
    log_file << "Line no " << lineNo << ": Token "<< "<STRING>" <<" Lexeme " << buf << " found --><STRING, "<<buf2 <<"> "<< endl;
    memset(buf, 0, sizeof(buf));
    memset(buf2, 0, sizeof(buf2));
}

void PrintConstChar(string lexeme, char c, int lineNo){
    token_file << "<CHAR_CONST, "<< c <<" > ";
    log_file << "Line no " << lineNo << ": Token "<< "<CHAR_CONST>" <<" Lexeme " << lexeme << " found --> <CHAR_CONST, "<< c <<"> "<< endl;
    SymbolInfo* symbol = new SymbolInfo(lexeme, "CHAR_CONST");
    bool inserted = symboltable->Insert(*symbol);
    if(inserted != false)
        symboltable->PrintAllTables(log_file);
    else
        log_file<<lexeme<<" already exists in current ScopeTable"<<endl;
}

#line 672 "1705043.c"
#line 673 "1705043.c"

#define INITIAL 0
#define str 1
#define strSlash 2
#define slashStar 3
#define slashSlash 4
#define slashSlashSlash 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 122 "1705043.l"

#line 124 "1705043.l"
 
#line 899 "1705043.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 170 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 334 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 125 "1705043.l"
{
            BEGIN (str);
            memset(buf, 0, sizeof(buf));
            memset(buf2, 0, sizeof(buf2));
            s = buf;
            s2 = buf2;
            *s++ = '\"';
            *s2++ = '\"';
            lineStart = lineCount;
            finished = false;
        }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 137 "1705043.l"
{PrintKeyword("IF", yytext, lineCount);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 138 "1705043.l"
{PrintKeyword("ELSE", yytext, lineCount);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 139 "1705043.l"
{PrintKeyword("FOR", yytext, lineCount);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 140 "1705043.l"
{PrintKeyword("WHILE", yytext, lineCount);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 141 "1705043.l"
{PrintKeyword("DO", yytext, lineCount);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 142 "1705043.l"
{PrintKeyword("BREAK", yytext, lineCount);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 143 "1705043.l"
{PrintKeyword("INT", yytext, lineCount);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 144 "1705043.l"
{PrintKeyword("CHAR", yytext, lineCount);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 145 "1705043.l"
{PrintKeyword("FLOAT", yytext, lineCount);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 146 "1705043.l"
{PrintKeyword("DOUBLE", yytext, lineCount);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 147 "1705043.l"
{PrintKeyword("VOID", yytext, lineCount);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 148 "1705043.l"
{PrintKeyword("RETURN", yytext, lineCount);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 149 "1705043.l"
{PrintKeyword("SWITCH", yytext, lineCount);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 150 "1705043.l"
{PrintKeyword("CASE", yytext, lineCount);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 151 "1705043.l"
{PrintKeyword("DEFAULT", yytext, lineCount);}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 152 "1705043.l"
{PrintKeyword("CONTINUE", yytext, lineCount);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 155 "1705043.l"
{PrintOperator("ADDOP", yytext, lineCount);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 156 "1705043.l"
{PrintOperator("MULOP", yytext, lineCount);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 157 "1705043.l"
{PrintOperator("INCOP", yytext, lineCount);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 158 "1705043.l"
{PrintOperator("RELOP", yytext, lineCount);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 159 "1705043.l"
{PrintOperator("ASSIGNOP", yytext, lineCount);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 160 "1705043.l"
{PrintOperator("LOGICOP", yytext, lineCount);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 161 "1705043.l"
{PrintOperator("NOT", yytext, lineCount);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 162 "1705043.l"
{PrintOperator("LPAREN", yytext, lineCount);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 163 "1705043.l"
{PrintOperator("RPAREN", yytext, lineCount);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 164 "1705043.l"
{PrintOperator("LCURL", yytext, lineCount);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 165 "1705043.l"
{PrintOperator("RCURL", yytext, lineCount);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 166 "1705043.l"
{PrintOperator("LTHIRD", yytext, lineCount);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 167 "1705043.l"
{PrintOperator("RTHIRD", yytext, lineCount);}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 168 "1705043.l"
{PrintOperator("COMMA", yytext, lineCount);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 169 "1705043.l"
{PrintOperator("SEMICOLON", yytext, lineCount);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 170 "1705043.l"
{}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 173 "1705043.l"
{
                BEGIN(slashStar);
                memset(buf, 0, sizeof(buf));
                memset(buf2, 0, sizeof(buf2));
                s= buf;
                *s++ = '/';
                *s++ = '*';
                lineStart = lineCount;
                finished = false;
             }
	YY_BREAK
case 35:
/* rule 35 can match eol */
YY_RULE_SETUP
#line 184 "1705043.l"
{
                        *s++ = *yytext; 
                        ++lineCount;
                    }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 188 "1705043.l"
{
                            *s++ = '*'; 
                            *s++ = '/'; 
                            BEGIN(INITIAL); 
                            *s=0; 
                            PrintComment(lineStart, false); 
                            finished = true;
                        }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 196 "1705043.l"
{*s++ = *yytext;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 199 "1705043.l"
{
            BEGIN (slashSlash);
            s= buf;
            *s++ = '/';
            *s++ = '/';
            lineStart = lineCount;
        }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 206 "1705043.l"
{
                    BEGIN (slashSlashSlash); 
                    *s++ = '\\';
                }
	YY_BREAK
case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
#line 210 "1705043.l"
{
/*                     *s++ = *yytext;  */
                    lineCount++; 
                    BEGIN(INITIAL); 
                    *s=0; 
                    PrintComment(lineStart, false);
                    finished = true;
                }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 219 "1705043.l"
{*s++ = *yytext; }
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 220 "1705043.l"
{
                        *s++ = *yytext; 
                        lineCount++; 
                        BEGIN(slashSlash);
                    }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 225 "1705043.l"
{
                    *s++ = *yytext; 
                    BEGIN(slashSlash);
                }
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 232 "1705043.l"
{++lineCount;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 233 "1705043.l"
{PrintIdentifier("ID", yytext, lineCount);}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 234 "1705043.l"
{PrintIdentifier("CONST_INT", yytext, lineCount);}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 235 "1705043.l"
{PrintIdentifier("CONST_FLOAT", yytext, lineCount);}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 237 "1705043.l"
{
                        char temp = yytext[2];
                        char c;
                        if(yytext[1]=='\\'){
                            if(temp=='n'){c='\n';}
                            else if(temp=='t'){c='\t';}
                            else if(temp=='a'){c='\a';}
                            else if(temp=='f'){c='\f';}
                            else if(temp=='b'){c='\b';}
                            else if(temp=='v'){c='\v';}
                            else if(temp=='r'){c='\r';}
                            else if(temp=='0'){c='\0';}
                            else if(temp=='\\'){c='\\';}
                            else if(temp=='\''){c='\'';}
                            else if(temp=='\"'){c='\"';}
                        }
                        else {c=yytext[1];}
                        
                        PrintConstChar(yytext, c, lineCount);
                    }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 258 "1705043.l"
{
                        log_file<<"Error at line no "<<lineCount<<" : Too many decimal points  "<<yytext<<endl; 
                        ++errorCount;
                    }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 263 "1705043.l"
{
                        log_file<<"Error at line no "<<lineCount<<" : Ill formed number  "<<yytext<<endl; 
                        ++errorCount;
                    }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 268 "1705043.l"
{
                        log_file<<"Error at line no "<<lineCount<<" : Invalid prefix on ID or invalid suffix on Number "<<yytext<<endl; 
                        ++errorCount;
                    }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 273 "1705043.l"
{
                                log_file<<"Error at line no "<<lineCount<<" : Multi character constant error "<<yytext<<endl; 
                                ++errorCount;
                            }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 278 "1705043.l"
{
                                    log_file<<"Error at line no "<<lineCount<<" : Unterminated character "<<yytext<<endl; 
                                    ++errorCount;
                                }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 283 "1705043.l"
{
                                log_file<<"Error at line no "<<lineCount<<" : Empty character constant error"<<yytext<<endl; 
                                ++errorCount;
                            }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 288 "1705043.l"
{
                *s++ = '\\';
                BEGIN (strSlash);    
            }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 293 "1705043.l"
{
                                    *s++ = *yytext;
                                    char temp = yytext[0];
                                    if(temp=='n'){*s2++='\n';}
                                    else if(temp=='t'){*s2++='\t';}
                                    else if(temp=='a'){*s2++='\a';}
                                    else if(temp=='f'){*s2++='\f';}
                                    else if(temp=='b'){*s2++='\b';}
                                    else if(temp=='v'){*s2++='\v';}
                                    else if(temp=='r'){*s2++='\r';}
                                    else if(temp=='0'){*s2++='\n';}
                                    else if(temp=='\\'){*s2++='\\';}
                                    else if(temp=='\''){*s2++='\'';}
                                    else if(temp=='\"'){*s2++='\"';}
                                    BEGIN (str);
                            }
	YY_BREAK
case 57:
/* rule 57 can match eol */
YY_RULE_SETUP
#line 309 "1705043.l"
{
                    ++lineCount;
                    *s++ = *yytext; 
                    BEGIN(str);
                }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 315 "1705043.l"
{
                    *s++ = *yytext;
                    *s2++ = *yytext;
                    BEGIN (str);
                }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 320 "1705043.l"
{
                *s++ = '\"';
                *s2++ = '\"';
                *s = 0;
                *s2 = 0;

                BEGIN (INITIAL);
                PrintString(lineStart);
                finished = true;   
                memset(buf, 0, sizeof(buf));
                memset(buf2, 0, sizeof(buf2));
            }
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 333 "1705043.l"
{
                *s = 0;
                *s2 = 0;
                lineCount++;
                BEGIN (INITIAL);
                 
                finished = true;
                log_file<<"Error at line no "<<lineStart<<" : Unterminated String "<<buf<<endl; 
                ++errorCount;
                memset(buf, 0, sizeof(buf));
                memset(buf2, 0, sizeof(buf2));
            }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 346 "1705043.l"
{
                *s++ = *yytext;
                *s2++ = *yytext;
            }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(str):
case YY_STATE_EOF(strSlash):
case YY_STATE_EOF(slashStar):
case YY_STATE_EOF(slashSlash):
case YY_STATE_EOF(slashSlashSlash):
#line 353 "1705043.l"
{
            if(finished==false){
                log_file<<"Error at line no "<<lineStart<<" : Unterminated Comment "<<buf<<endl; 
                ++errorCount;
                memset(buf, 0, sizeof(buf));
                memset(buf2, 0, sizeof(buf2));
            }

            symboltable->PrintAllTables(log_file);
            log_file<<"Total lines : "<<lineCount<<endl;
            log_file<<"Total errors : "<<errorCount<<endl;
            return 0;
        }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 367 "1705043.l"
{
                                log_file<<"Error at line no "<<lineCount<<" : Unrecognized character "<<yytext<<endl; 
                                ++errorCount;
                            }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 372 "1705043.l"
ECHO;
	YY_BREAK
#line 1441 "1705043.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 170 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 170 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 169);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 372 "1705043.l"

int main(int argc,char *argv[]){
	
	if(argc!=2){
		printf("Please provide input file name and try again\n");
		return 0;
	}
	
	FILE *fin=fopen(argv[1],"r");
	if(fin==NULL){
		printf("Cannot open specified file\n");
		return 0;
	}
	

	yyin= fin;
	yylex();
	fclose(yyin);
	return 0;
}

